# Mi archivo de configuración de kitty :D

# Tipografías

font_family       MonaspaceNeon
font_size         11
disable_ligatures never
font_features MonaspaceNeon-Regular +calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10 +liga

# Estética

window_padding_width 		8
hide_window_decorations 	yes
background_opacity 			0.7 
url_style 					curly
cursor_trail 				1

# Colores

include colors.conf

# Comportamiento

confirm_os_window_close 0
