# Mi archivo de configuración de kitty :D

# Colores

include colors.conf

# Fuentes

font_family       family="Monaspace Neon"
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         11
disable_ligatures never

# Padding de ventana

window_padding_width 8

# Cierre de ventana

confirm_os_window_close 0
